#source ./env_pvc.sh

#
# This works with AFAR 2146, Do not increase the Optimization beyond -O1

OPT="-O3"


# -fgpu-rdc is needed for some reason when working with the AFAR compiler
cmake -DHEMELB_GPU_BACKEND=SYCL \
        -DHEMELB_SYCL_TARGET=spir64 \
        -DHEMELB_SYCL_ARCH=pvc \
        -DCMAKE_CXX_COMPILER=icpx \
        -DCMAKE_CXX_FLAGS="${OPT} ${MPI_CFLAGS}" \
        -DCMAKE_C_COMPILER=icx \
        -DCMAKE_C_FLAGS="${OPT} ${MPI_CFLAGS}" \
        -DCMAKE_EXE_LINKER=icpx \
        -DCMAKE_EXE_LINKER_FLAGS="${OPT} ${MPI_LDFLAGS}" \
        -DHEMELB_COMPUTE_ARCHITECTURE=NEUTRAL \
        -DCMAKE_CXX_EXTENSIONS=OFF \
        -DHEMELB_CUDA_AWARE_MPI=ON \
        -DHEMELB_LOG_LEVEL="Info" \
        -DHEMELB_USE_MPI_PARALLEL_IO=ON \
        -DHEMELB_USE_VELOCITY_WEIGHTS_FILE="OFF" \
        -DHEMELB_INLET_BOUNDARY="NASHZEROTHORDERPRESSUREIOLET" \
        -DHEMELB_OUTLET_BOUNDARY="NASHZEROTHORDERPRESSUREIOLET" \
        -DHEMELB_WALL_INLET_BOUNDARY="NASHZEROTHORDERPRESSURESBB" \
        -DHEMELB_WALL_OUTLET_BOUNDARY="NASHZEROTHORDERPRESSURESBB" \
        ..

cmake --build . -j 16  -v

