source ../env_crusher_afar.sh
OPT="-g -ggdb -O3"

cmake -DHEMELB_GPU_BACKEND=HIP_ROCM \
		 -DCMAKE_CXX_COMPILER=$ROCM_PATH/llvm/bin/amdclang++ \
		 -DCMAKE_CXX_FLAGS="${OPT} ${MPI_CFLAGS}" \
		 -DCMAKE_C_COMPILER=$ROCM_PATH/llvm/bin/amdclang  \
		 -DCMAKE_C_FLAGS="${OPT} ${MPI_CFLAGS}" \
		 -DHEMELB_COMPUTE_ARCHITECTURE=NEUTRAL \
		 -DCMAKE_CXX_EXTENSIONS=OFF \
		 -DHEMELB_CUDA_AWARE_MPI=ON \
		 -DCMAKE_HIP_COMPILER=$ROCM_PATH/llvm/bin/amdclang++ \
		 -DCMAKE_HIP_FLAGS="${OPT} ${MPI_CFLAGS} --offload-arch=gfx90a" \
		 -DCMAKE_EXE_LINKER_FLAGS="${OPT} ${MPI_LDFLAGS} --offload-arch=gfx90a" \
		 -DHIP_CLANG_PATH=${ROCM_PATH}/llvm/bin \
		-DHEMELB_LOG_LEVEL="Info" \
		-DHEMELB_USE_MPI_PARALLEL_IO=ON \
		-DHEMELB_USE_VELOCITY_WEIGHTS_FILE="ON" \
     -DHEMELB_INLET_BOUNDARY="LADDIOLET" \
     -DHEMELB_OUTLET_BOUNDARY="NASHZEROTHORDERPRESSUREIOLET" \
     -DHEMELB_WALL_INLET_BOUNDARY="LADDIOLETSBB" \
     -DHEMELB_WALL_OUTLET_BOUNDARY="NASHZEROTHORDERPRESSURESBB" \
     -DHEMELB_WALL_BOUNDARY="SIMPLEBOUNCEBACK" \
		..

cmake --build . -j 16  -v
