source ../../env.sh

cmake -DHEMELB_GPU_BACKEND=CUDA \
		 -DCMAKE_CXX_COMPILER=mpicxx \
		 -DCMAKE_C_COMPILER=mpicc \
		 -DCMAKE_CUDA_ARCHITECTURES="90" \
		 -DHEMELB_COMPUTE_ARCHITECTURE=NEUTRAL \
		 -DCMAKE_CXX_EXTENSIONS=OFF \
		 -DHEMELB_CUDA_AWARE_MPI=ON \
 		 -DHEMELB_LOG_LEVEL="Info" \
	 	 -DHEMELB_USE_MPI_PARALLEL_IO=OFF \
     -DHEMELB_USE_VELOCITY_WEIGHTS_FILE="ON" \
	   -DCMAKE_BUILD_TYPE=Release \
     -DHEMELB_INLET_BOUNDARY="LADDIOLET" \
     -DHEMELB_OUTLET_BOUNDARY="NASHZEROTHORDERPRESSUREIOLET" \
     -DHEMELB_WALL_INLET_BOUNDARY="LADDIOLETSBB" \
     -DHEMELB_WALL_OUTLET_BOUNDARY="NASHZEROTHORDERPRESSURESBB" \
     -DHEMELB_WALL_BOUNDARY="SIMPLEBOUNCEBACK" \
     -DHEMELB_KERNEL="LBGKSL" \
     ..

cmake --build . -j 16  -v
