source ../env_summit.sh

cmake -DHEMELB_GPU_BACKEND=CUDA \
		 -DCMAKE_CXX_COMPILER=mpicxx \
		 -DCMAKE_C_COMPILER=mpicc \
	   -DCMAKE_CXX_STANDARD=17 \
		 -DHEMELB_COMPUTE_ARCHITECTURE=NEUTRAL \
		 -DCMAKE_CXX_EXTENSIONS=OFF \
		 -DHEMELB_CUDA_AWARE_MPI=OFF \
		 -DHEMELB_LOG_LEVEL="Info" \
		 -DHEMELB_USE_MPI_PARALLEL_IO=ON \
     -DHEMELB_USE_VELOCITY_WEIGHTS_FILE="ON" \
     -DHEMELB_INLET_BOUNDARY="LADDIOLET" \
     -DHEMELB_OUTLET_BOUNDARY="NASHZEROTHORDERPRESSUREIOLET" \
     -DHEMELB_WALL_INLET_BOUNDARY="LADDIOLETSBB" \
     -DHEMELB_WALL_OUTLET_BOUNDARY="NASHZEROTHORDERPRESSURESBB" \
		 -DHEMELB_WALL_BOUNDARY="SIMPLEBOUNCEBACK" \
		 -DCMAKE_CUDA_COMPILER=nvcc \
		 -DCMAKE_CUDA_ARCHITECTURES=70 \
		 -DHEMELB_USE_SSE3="OFF" \
		..

cmake --build . -j 16  -v
